#!/bin/bash
# Commandes à exécuter sur la Freebox après synchronisation

echo "═══════════════════════════════════════════════════════════"
echo "    COMMANDES À EXÉCUTER SUR LA FREEBOX"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "1️⃣  Vérifier que les fichiers ont été synchronisés:"
echo "    cd /home/bagbot/Bag-bot"
echo "    ls -l src/commands/dashboard.js"
echo ""
echo "2️⃣  Redémarrer le bot Discord:"
echo "    pm2 restart bag-bot"
echo "    pm2 logs bag-bot --lines 20"
echo ""
echo "3️⃣  Redémarrer le dashboard:"
echo "    pm2 restart dashboard"
echo "    pm2 logs dashboard --lines 20"
echo ""
echo "4️⃣  Vérifier l'état des services:"
echo "    pm2 status"
echo ""
echo "5️⃣  Tester la commande /dashboard sur Discord"
echo "    → Le lien devrait maintenant pointer vers:"
echo "    → http://88.174.155.230:3002"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "    EN CAS DE PROBLÈME - RESTAURATION"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Restaurer les sauvegardes (si nécessaire):"
echo ""
echo "cp src/commands/dashboard.js.backup src/commands/dashboard.js"
echo "cp src/utils/discord_gif_downloader.js.backup src/utils/discord_gif_downloader.js"
echo "cp dashboard-v2/server-v2.js.backup dashboard-v2/server-v2.js"
echo "cp dashboard-v2/index.html.backup dashboard-v2/index.html"
echo "cp dashboard-v2/auto_download_discord_gifs.js.backup dashboard-v2/auto_download_discord_gifs.js"
echo ""
echo "Puis redémarrer les services:"
echo "pm2 restart bag-bot dashboard"
echo ""
echo "═══════════════════════════════════════════════════════════"
